# dev branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
interface = "0.0.0.0"
port = 8180
[dapps]
cors = "all"
interface = "0.0.0.0"
hosts = ["all"]
port = 8080
[account]
password = ["node.pwd"]
[mining]
force_sealing = true
engine_signer = "0xF982f6ac73a26e243B7D26E0388B104817f75933"
reseal_on_txs = "none"
[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"
