[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity"

[network]
port = 30300

[rpc]
interface = "0.0.0.0"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
interface = "0.0.0.0"
port = 8180

[dapps]
interface = "0.0.0.0"
hosts = ["all"]
port = 8080

[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "none"
