[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity"

[network]
port = 30300
bootnodes = ["enode://c7e752201bf4238b69a0583af2f1ff0ed363b2eb80d9f4744e6f2af7fac85d8e38cd4be76b2017abe6bc1206aa9d1b6aeaa9be86ff1707e88fa8ff7201967fd4@172.16.13.64.241.133:30300"]

[rpc]
interface = "0.0.0.0"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[ui]
interface = "0.0.0.0"
port = 8180

[dapps]
interface = "0.0.0.0"
hosts = ["all"]
port = 8080

[account]
password = ["node.pwds"]
[mining]
force_sealing = true
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
reseal_on_txs = "none"
