[parity]
chain = "spec.json"
base_path = "parity"
# db_path = "parity/chains"
# keys_path = "parity/keys"
[network]
bootnodes=["enode://0efbed017015be3ef61442e4734f931b5e3c6263ff4c3548abc261830a29e2e7bb09bd1489787ef02aff5c651a958d2f8e6ebf6178b58efb54ca2cff6ee9b892@40.114.53.209:30300"]
port = 30300
[rpc]
cors = "all"
interface = "0.0.0.0"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
# [ui]
# interface = "0.0.0.0"
# port = 8180
# [dapps]
# cors = "all"
# interface = "0.0.0.0"
# hosts = ["all"]
# port = 8080
# path = "parity/dapps"
