# dev branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
bootnodes=["enode://e0e941c20d08d552d5827ebe785d8017d5260ff8d0056b49a8eb126be8ef14a5c1f271679dc3c30b2739f041aa73ee3f7d78479cfc5da53556fbb12184cf73d0@52.168.166.77:30300"]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
