# TestTestNet-2 branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
bootnodes=["enode://7814abe177207c037db5ee962536df2724ec605364d415a5d25438f28afe374194bac829b1683db468539cdf3a442ffb46ebc26e24658c0d4cb0e9b2b9327fe9@52.170.205.143:30300"]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
